name: "Jamie Kirkpatrick"
email: "jkp@kirkconsulting.co.uk"
signingkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3WPGoCPxY5zjzjh0LEwfPAuK58dngHL4YKCNsCvGG6djvwRzgElxtj4kFsIzsxmR2djh9xeAA6pDEhgjcBZbylGhmEPf9q8ORWpug+zOwl2/lNQp7qTEAh6OmToiOjSwPNZSe1xci7IXnzlSs47BYBw5WJ1NIX/h+GNKIwgPt9o64kylMoOT+v3puX8DaoOKjE1rI2jYBh7CsvrD8+g/K0YbXjWy9bHabWnSH+7KWkGzd6+MZJ/Oe0SJUu+ck2DA8wWGkMfop0z6n9vsZa2USIjB5uSIDzN6ldEz5sIaPvqAaJ/0mdoz9aYEinh/rgAa8uOtsSpTlBW1b1x2N+6pR"
